Force gnu++98
To fix compilation bug on modern compilers:
src/SerialPort.h:74:18: error: ‘template<class> class std::auto_ptr’ is deprecated [-Werror=deprecated-declarations]
     typedef std::auto_ptr<SerialPort> Ptr;
Because:
"The default mode for C++ is now -std=gnu++14 instead of -std=gnu++98."